### ISSUE TITLE
Crash when using multiple item classes

### ISSUE THREAD

**Issue by denimwho** [afollestad/recyclical#13]
Library Version: 

0.7.2
 
Affected Device(s):
 
Redmi Note 4 with Android 9.0
 
Describe the Bug:
```
java.lang.IllegalStateException: Didn't find type for class [Ljava.lang.Object;
        at com.afollestad.recyclical.handle.RealRecyclicalHandle.getViewTypeForClass(RealRecyclicalHandle.kt:69)
        at com.afollestad.recyclical.internal.DefinitionAdapter.getItemType(DefinitionAdapter.kt:86)
        at com.afollestad.recyclical.internal.DefinitionAdapter.getItemViewType(DefinitionAdapter.kt:59)
```
I get the above exception when trying to use multiple view types.

Recycler View code:

```
private fun setupRecyclerView(it: ContactDetail) {
        rv_contact_detail.setup {
            withDataSource(dataSourceOf(it.phoneNumbers, it.addresses))

            withItem<PhoneNumber>(R.layout.item_double) {
                onBind(::NumberHolder) { index, item ->
                    tvPrimary.text = item.number.toString()
                    tvSec.text = item.type
                }
            }

            withItem<Address>(R.layout.item_address) {
                onBind(::AddressHolder) { index, item ->
                    tvPrimary.text = item.address
                    tvSec.text = item.type
                }
            }
        }
    }


```

**Comment by denimwho** [comment]
Fixed the above issue by changing data source code.

Before:
`withDataSource(dataSourceOf(phoneNumbers, addresses))`

After:
```
val dataSource = emptyDataSource()
dataSource.addAll(phoneNumbers)
dataSource.addAll(addresses)
```

**Comment by afollestad** [comment]
That's definitely not intended behavior

**Comment by afollestad** [comment]
Oh, those two values given are arrays/lists - then yeah that isn't supported

**Comment by afollestad** [comment]
Although if they're arrays you may be able to use Kotlin's spread operator (*):

```kotlin
fun methodThatAcceptsVarargs(vararg items: String) { 
    ...
}

val myArray: Array<String> = // ...
methodThatAcceptsVarargs(*myArray)
```
