### ISSUE TITLE
Crash wile remove item from the datasource

### ISSUE THREAD

**Issue by philippMarchenko** [afollestad/recyclical#36]
*Please consider making a Pull Request if you are capable of doing so.*

**Library Version:**

1.1.1
 
**Affected Device(s):**
 
Xiaomi redmi 4x
 
**Describe the Bug:**

If I remove item from datasource in second time - I get crash  java.lang.IndexOutOfBoundsException: Index: 6, Size: 6

**To Reproduce:**
1. datasource has 7 items
2. Remove 6 item from datasource
3. Try to remove last item - got crash

`onBind(::FullListViewHolder) { index, item ->
                    this.bind(index, item, {
                        dataSource.removeAt(it)
                    })
                }`

`fun bind(
        index: Int,
        item: InvestmentModel,
        onDeleteClick:(Int) -> Unit
    ){
        itemView.tvDelete?.setOnClickListener {
            onDeleteClick(index)
        }
    }`

**Comment by zunjae** [comment]
I got the same crash

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
       at java.util.ArrayList.get(ArrayList.java:439)
       at com.afollestad.recyclical.datasource.RealDataSource.get(RealDataSource.java:2)
       at com.afollestad.recyclical.viewholder.NoSelectionStateProvider.getItem(NoSelectionStateProvider.java:8)
```

how did you fix it?
